### ISSUE TITLE
Cannot build with cmake in MacOS

### ISSUE THREAD

**Issue by OskarSigvardsson** [ekpyron/pbf#3]
Hello! I just came across this project because I wanted to do something similar myself. I tried cloning it and building running cmake to build it, but I got this error: 

    CMake Error at CMakeLists.txt:13 (add_subdirectory):
      The source directory

        /<my local path>/pbf/libs/spdlog

      does not contain a CMakeLists.txt file.

I'm really curious to check this out and play with it, so any help with building it would be very appreciated. I'm on MacOS, i'm using `cmake` installed using homebrew. Thanks!

**Comment by clonker** [comment]
Hi! Spdlog is included as a submodule, so you would have to do a
```bash
git submodule update --init
```
beforehand. However you should know that this project requires OpenGL 4.3  and AFAIK macOS only supports up to 4.1. If you have a recent enough graphics card (which should be any non-ancient AMD or nvidia discrete card) you should be able to compile it on at least linux and with the help of mingw or something alike probably on windows too.

**Comment by OskarSigvardsson** [comment]
Ah, obviously, I feel stupid now :) You're probably right about MacOS, though. I have windows installed using Bootcamp, and I think the drivers there support 4.3, though I'm not certain. I'll try building it there. 

Thanks for the response!

**Comment by clonker** [comment]
Cheers!
